/* ═══════════════════════════════════════
   data4.js — نسخه ۴.۱ (روش push مستقیم)
   ═══════════════════════════════════════ */

MANUALS.push(
{id:"r8",title:"تعویض Ion Chamber مانیتور دوم",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-560",duration:"۲ ساعت",level:"متوسط",
 summary:"تعویض اتاقک یونیزاسیون دوم در مسیر پرتو.",
 warn:"پس از تعویض، کالیبراسیون دز انجام شود.",
 tools:["پیچ‌گوشتی Torx","دستکش","فیلر","مولتی‌متر"],
 steps:[
   {t:"خاموشی و انتظار سرد شدن"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن کابل HV و سیگنال"},
   {t:"باز کردن پیچ‌ها"},
   {t:"نصب اتاقک جدید",level:"warn",note:"هم‌ترازی با اتاقک اول"},
   {t:"اتصال و بستن پنل"},
   {t:"Daily QA و کالیبراسیون مجدد"}
 ]},
{id:"r9",title:"تعویض Head Cable Assembly",cat:"replace",machines:["Synergy","Infinity"],code:"REP-565",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض کابل‌های Head شامل HV، سیگنال و خنک‌کننده.",
 warn:"کابل‌ها باید دقیقاً با Part Number یکسان باشند.",
 tools:["دستکش ESD","پیچ‌گوشتی","برچسب"],
 steps:[
   {t:"خاموشی کامل و برچسب‌گذاری"},
   {t:"عکس گرفتن از اتصالات"},
   {t:"جدا کردن کابل‌های HV",level:"warn"},
   {t:"جدا کردن سیگنال"},
   {t:"نصب کابل‌های جدید طبق عکس"},
   {t:"تست پیوستگی"},
   {t:"QA کامل"}
 ]},
{id:"r10",title:"تعویض Bending Magnet",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-570",duration:"۶ ساعت",level:"پیشرفته",
 summary:"تعویض آهنربای خمشی که مسیر الکترون را تصحیح می‌کند.",
 warn:"هماهنگی با Elekta Service. جرثقیل لازم است.",
 tools:["جرثقیل کوچک","آچار تورک","Alignment Tool"],
 steps:[
   {t:"خاموشی کامل و تخلیه خازن‌ها",level:"danger"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن اتصالات آب"},
   {t:"باز کردن پیچ‌ها"},
   {t:"خارج کردن با جرثقیل",level:"warn"},
   {t:"نصب Magnet جدید"},
   {t:"اتصال آب و تست نشتی"},
   {t:"Auto-Conditioning و کالیبراسیون"}
 ]},
{id:"r11",title:"تعویض Filament Transformer",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-575",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض ترانس Filament که تغذیه گرم‌کننده را تأمین می‌کند.",
 warn:"ولتاژ خطرناک. تخلیه کامل قبل از کار.",
 tools:["مولتی‌متر","پیچ‌گوشتی","دستکش ESD"],
 steps:[
   {t:"خاموشی و تخلیه خازن‌ها",level:"danger"},
   {t:"برچسب‌گذاری سیم‌ها"},
   {t:"جدا کردن اتصالات"},
   {t:"باز کردن پیچ‌ها"},
   {t:"نصب Transformer جدید"},
   {t:"اتصال طبق برچسب"},
   {t:"تست ولتاژ خروجی"},
   {t:"Auto-Conditioning"}
 ]},
{id:"r12",title:"تعویض Water Manifold",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-580",duration:"۴ ساعت",level:"پیشرفته",
 summary:"تعویض توزیع‌کننده آب خنک‌کننده Head.",
 warn:"خطر نشتی آب و آسیب الکترونیکی.",
 tools:["آچار مخصوص","دستمال جاذب","رگولاتور"],
 steps:[
   {t:"خاموشی و تخلیه آب",level:"warn"},
   {t:"برچسب‌گذاری لوله‌ها"},
   {t:"جدا کردن لوله‌ها"},
   {t:"باز کردن Manifold قدیمی"},
   {t:"نصب Manifold جدید"},
   {t:"اتصال لوله‌ها"},
   {t:"پر کردن آب و تست نشتی"},
   {t:"QA"}
 ]},
{id:"t11",title:"عیب‌یابی خطای Motor Overload",cat:"trouble",machines:["Synergy","Infinity"],code:"TRB-700",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"رفع خطای Overload در موتورهای Gantry، Collimator، Jaw یا MLC.",
 tools:["مولتی‌متر","چک‌لیست Motor","دماسنج"],
 steps:[
   {t:"شناسایی Motor مشکل‌دار از Log"},
   {t:"بررسی دمای Motor",note:"بالای ۸۰°C غیرعادی"},
   {t:"بررسی بار مکانیکی"},
   {t:"اندازه‌گیری جریان"},
   {t:"بررسی اتصالات"},
   {t:"Reset و تست"},
   {t:"تعویض در صورت تکرار"}
 ]},
{id:"t12",title:"عیب‌یابی خطای Temperature Sensor",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-705",duration:"۳۰ دقیقه",level:"متوسط",
 summary:"رفع خطاهای سنسور دما.",
 tools:["مولتی‌متر","متر دما مرجع"],
 steps:[
   {t:"ثبت شماره سنسور"},
   {t:"اندازه‌گیری با متر مرجع"},
   {t:"مقایسه با خوانش",note:"اختلاف ± ۲°C"},
   {t:"بررسی اتصالات"},
   {t:"تست پیوستگی"},
   {t:"تعویض در صورت انحراف"},
   {t:"کالیبراسیون"}
 ]},
{id:"t13",title:"عیب‌یابی مشکل ارتباط سریال",cat:"trouble",machines:["Synergy","Infinity"],code:"TRB-710",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"رفع خطاهای RS-232 یا RS-485.",
 tools:["مولتی‌متر","RS-232 Tester"],
 steps:[
   {t:"بررسی کابل"},
   {t:"تست Pin‌ها"},
   {t:"اندازه‌گیری ولتاژ (± ۵-۱۲V)"},
   {t:"تست با Tester"},
   {t:"ری‌استارت سرویس"},
   {t:"بررسی Baud Rate"},
   {t:"تعویض کابل در صورت نیاز"}
 ]},
{id:"t14",title:"عیب‌یابی خطای Axial Movement",cat:"trouble",machines:["Synergy","Infinity"],code:"TRB-715",duration:"۶۰ دقیقه",level:"پیشرفته",
 summary:"رفع خطاهای حرکت محوری میز.",
 tools:["مولتی‌متر","فیلر"],
 steps:[
   {t:"بررسی کد خطا"},
   {t:"تست حرکت محور Long"},
   {t:"بررسی Encoder"},
   {t:"بررسی Motor Drive"},
   {t:"کالیبراسیون موقعیت صفر"},
   {t:"تست Load Tolerance"},
   {t:"QA"}
 ]},
{id:"t15",title:"عیب‌یابی Radiation Monitor",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-720",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"رفع خطاهای Radiation Monitor اتاق.",
 tools:["Survey Meter مرجع"],
 steps:[
   {t:"بررسی منبع تغذیه"},
   {t:"تست Signal"},
   {t:"مقایسه با Survey Meter"},
   {t:"بررسی کالیبراسیون"},
   {t:"بررسی کابل"},
   {t:"Reset"},
   {t:"کالیبراسیون مجدد"}
 ]},
{id:"s7",title:"تعویض Bending Magnet Synergy",cat:"synergy",machines:["Synergy"],code:"SYN-REP-03",duration:"۶ ساعت",level:"پیشرفته",
 summary:"تعویض Bending Magnet در Synergy.",
 warn:"هماهنگی با Elekta Service الزامی است.",
 tools:["جرثقیل","آچار تورک","Alignment Tool"],
 steps:[
   {t:"خاموشی و برچسب",level:"danger"},
   {t:"تخلیه خازن‌ها"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن اتصالات"},
   {t:"خارج کردن Magnet",level:"warn"},
   {t:"نصب Magnet جدید"},
   {t:"تنظیم Alignment"},
   {t:"Auto-Conditioning و کالیبراسیون"}
 ]},
{id:"s8",title:"تعویض Backup Chain Assembly",cat:"synergy",machines:["Synergy"],code:"SYN-REP-04",duration:"۵ ساعت",level:"پیشرفته",
 summary:"تعویض زنجیر پشتیبان مکانیزم در Synergy.",
 warn:"زنجیر تحت کشش است.",
 tools:["آچار مخصوص","ابزار کشش","گریس زنجیر"],
 steps:[
   {t:"خاموشی و قفل مکانیکی"},
   {t:"علامت‌گذاری موقعیت"},
   {t:"آزاد کردن کشش"},
   {t:"باز کردن زنجیر قدیمی"},
   {t:"نصب زنجیر جدید"},
   {t:"تنظیم کشش"},
   {t:"گریس‌کاری"},
   {t:"تست حرکت"}
 ]},
{id:"s9",title:"عیب‌یابی خطای Synergy Motor",cat:"synergy",machines:["Synergy"],code:"SYN-TRB-02",duration:"۹۰ دقیقه",level:"متوسط",
 summary:"رفع خطاهای Motor در Synergy.",
 tools:["مولتی‌متر","نرم‌افزار Service"],
 steps:[
   {t:"ثبت کد خطا"},
   {t:"بررسی Log"},
   {t:"بررسی Encoder"},
   {t:"بررسی Drive Board"},
   {t:"تست Motor آهسته"},
   {t:"Reset"},
   {t:"کالیبراسیون"}
 ]},
{id:"i8",title:"کالیبراسیون Verifying XV",cat:"infinity",machines:["Infinity"],code:"INF-CAL-02",duration:"۶۰ دقیقه",level:"پیشرفته",
 summary:"کالیبراسیون Verifying XV برای تأیید موقعیت بیمار.",
 warn:"نیازمند فانتوم کالیبراسیون XV.",
 tools:["فانتوم XV","XVI Service"],
 steps:[
   {t:"نصب فانتوم در Isocenter"},
   {t:"Service → Verifying XV"},
   {t:"اجرای اسکن"},
   {t:"تحلیل نتایج",note:"انحراف زیر ۱mm"},
   {t:"تست Marker"},
   {t:"ذخیره"},
   {t:"QA Verify"}
 ]},
{id:"i9",title:"تعویض Motor Klystron Cooling",cat:"infinity",machines:["Infinity"],code:"INF-REP-02",duration:"۲ ساعت",level:"متوسط",
 summary:"تعویض موتور فن خنک‌کننده Klystron.",
 warn:"دستگاه باید سرد باشد.",
 tools:["پیچ‌گوشتی","آچار مخصوص"],
 steps:[
   {t:"خاموشی و سرد شدن"},
   {t:"باز کردن پنل"},
   {t:"جدا کردن کابل"},
   {t:"باز کردن پیچ‌ها"},
   {t:"نصب فن جدید"},
   {t:"اتصال"},
   {t:"تست چرخش"},
   {t:"QA"}
 ]},
{id:"i10",title:"عیب‌یابی خطای Aperture",cat:"infinity",machines:["Infinity"],code:"INF-TRB-02",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"رفع خطاهای Aperture در Infinity.",
 tools:["مولتی‌متر","Service"],
 steps:[
   {t:"ثبت کد خطا"},
   {t:"بررسی Log"},
   {t:"تست حرکت Aperture"},
   {t:"بررسی Encoder و Motor"},
   {t:"بررسی کالیبراسیون"},
   {t:"Reset"},
   {t:"کالیبراسیون در صورت تکرار"}
 ]},
{id:"rf6",title:"تعویض Filament Transformer RF",cat:"rf",machines:["Synergy","Infinity","Versa HD"],code:"RF-005",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض ترانس Filament در بخش RF.",
 warn:"خطر HV. تخلیه کامل.",
 tools:["مولتی‌متر HV","پیچ‌گوشتی"],
 steps:[
   {t:"خاموشی و تخلیه",level:"danger"},
   {t:"برچسب سیم‌ها"},
   {t:"جدا کردن اتصالات"},
   {t:"تعویض Transformer"},
   {t:"اتصال طبق برچسب"},
   {t:"تست ولتاژ"},
   {t:"Auto-Conditioning"}
 ]},
{id:"rf7",title:"تنظیم Bending Magnet Current",cat:"rf",machines:["Synergy","Infinity"],code:"RF-006",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"تنظیم جریان Bending Magnet.",
 warn:"نیازمند Gaussmeter دقیق.",
 tools:["Gaussmeter","مولتی‌متر","Service"],
 steps:[
   {t:"Warm-up"},
   {t:"اندازه‌گیری میدان فعلی"},
   {t:"مقایسه با مرجع"},
   {t:"تنظیم جریان"},
   {t:"تست پایداری"},
   {t:"بررسی Beam"},
   {t:"QA"}
 ]},
{id:"rf8",title:"تعویض Waveguide Flange",cat:"rf",machines:["Synergy","Infinity","Versa HD"],code:"RF-007",duration:"۲ ساعت",level:"متوسط",
 summary:"تعویض Flange پس از نشتی یا آسیب.",
 warn:"تخلیه SF6 الزامی.",
 tools:["آچار تورک","کیت اورینگ","گریس","Detector"],
 steps:[
   {t:"خاموشی و تخلیه SF6"},
   {t:"برچسب Flange"},
   {t:"باز کردن پیچ‌ها"},
   {t:"بررسی سطح فلنج"},
   {t:"نصب Flange جدید"},
   {t:"بستن با تورک"},
   {t:"شارژ SF6"},
   {t:"تست نشتی ۲۴ ساعته"}
 ]},
{id:"e6",title:"تعویض Motor Drive Board",cat:"electronic",machines:["Synergy","Infinity"],code:"ELC-006",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تعویض برد درایو موتور.",
 tools:["دستکش ESD","پیچ‌گوشتی"],
 steps:[
   {t:"خاموشی و قفل"},
   {t:"عکس گرفتن"},
   {t:"جدا کردن کابل‌ها"},
   {t:"تعویض Board"},
   {t:"اتصال"},
   {t:"تنظیم پارامترها"},
   {t:"کالیبراسیون و QA"}
 ]},
{id:"e7",title:"تعویض Resolver Board",cat:"electronic",machines:["Synergy","Infinity"],code:"ELC-007",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"تعویض برد Resolver.",
 tools:["دستکش ESD","پیچ‌گوشتی"],
 steps:[
   {t:"خاموشی و قفل"},
   {t:"باز کردن پنل"},
   {t:"جدا کردن Resolver"},
   {t:"تعویض Board"},
   {t:"اتصال"},
   {t:"کالیبراسیون موقعیت"},
   {t:"تست دقت"}
 ]},
{id:"e8",title:"تشخیص خطای Voltage Regulator",cat:"electronic",machines:["Synergy","Infinity","Versa HD"],code:"ELC-008",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"عیب‌یابی Voltage Regulator.",
 tools:["مولتی‌متر","اسکوپ"],
 steps:[
   {t:"اندازه‌گیری ولتاژ"},
   {t:"بررسی Ripple",note:"زیر ۵۰mV"},
   {t:"مقایسه با مشخصات"},
   {t:"بررسی بار"},
   {t:"بررسی اتصالات"},
   {t:"تعویض در صورت انحراف"},
   {t:"تست سیستم"}
 ]},
{id:"mec7",title:"تنظیم Couch Backlash",cat:"mech",machines:["Synergy","Infinity"],code:"MEC-007",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"تنظیم Backlash میز درمان.",
 tools:["Service","فیلر دقیق"],
 steps:[
   {t:"اجرای تست Backlash"},
   {t:"بررسی مقادیر"},
   {t:"تنظیم در صورت انحراف",level:"warn"},
   {t:"تست مجدد"},
   {t:"کالیبراسیون"},
   {t:"Load Tolerance"}
 ]},
{id:"mec8",title:"تعویض Belt Drive Collimator",cat:"mech",machines:["Synergy","Infinity"],code:"MEC-008",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض تسمه محرک Collimator.",
 warn:"Collimator تحت کشش است.",
 tools:["آچار مخصوص","ابزار کشش"],
 steps:[
   {t:"خاموشی و قفل"},
   {t:"باز کردن پنل"},
   {t:"آزاد کردن کشش"},
   {t:"تعویض تسمه"},
   {t:"تنظیم کشش"},
   {t:"تست چرخش"},
   {t:"کالیبراسیون"}
 ]},
{id:"mec9",title:"تنظیم Gantry Balance",cat:"mech",machines:["Synergy","Infinity","Versa HD"],code:"MEC-009",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تنظیم تعادل Gantry.",
 warn:"تست چرخش کامل الزامی.",
 tools:["وزنه تعادل","مولتی‌متر"],
 steps:[
   {t:"قفل Gantry در صفر"},
   {t:"اندازه‌گیری گشتاور"},
   {t:"افزودن یا حذف وزنه"},
   {t:"تست چرخش کامل"},
   {t:"بررسی جریان Motor"},
   {t:"ثبت در فرم"}
 ]},
{id:"sw6",title:"راه‌اندازی DICOM Server",cat:"software",machines:["Synergy","Infinity","Versa HD"],code:"SW-006",duration:"۲ ساعت",level:"متوسط",
 summary:"راه‌اندازی DICOM Server برای تبادل با ARIA/PACS.",
 tools:["Admin","اطلاعات شبکه"],
 steps:[
   {t:"پیکربندی IP و Port"},
   {t:"تعیین AE Title"},
   {t:"پیکربندی Storage"},
   {t:"تست DICOM Echo"},
   {t:"تست ارسال CT"},
   {t:"تست RT Plan"},
   {t:"تست دریافت Patient Data"},
   {t:"ثبت"}
 ]},
{id:"sw7",title:"عیب‌یابی Database Corruption",cat:"software",machines:["Synergy","Infinity"],code:"SW-007",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"رفع خرابی دیتابیس.",
 warn:"قبل از هر اقدام، Backup تهیه کن.",
 tools:["Repair Tool","Backup اخیر"],
 steps:[
   {t:"Backup فوری"},
   {t:"بررسی لاگ"},
   {t:"Check Database"},
   {t:"Repair"},
   {t:"بررسی نتیجه"},
   {t:"در صورت شکست: Restore"},
   {t:"تست کامل"}
 ]},
{id:"sw8",title:"راه‌اندازی Backup خودکار",cat:"software",machines:["Synergy","Infinity","Versa HD"],code:"SW-008",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"راه‌اندازی Backup خودکار.",
 tools:["Admin","فضای ذخیره"],
 steps:[
   {t:"تعیین زمان"},
   {t:"تعیین مقصد"},
   {t:"پیکربندی در Service"},
   {t:"فعال‌سازی Auto Backup"},
   {t:"تست اولین اجرا"},
   {t:"بررسی فایل"},
   {t:"تنظیم نگهداری"}
 ]},
{id:"em6",title:"قطع آب خنک‌کننده اضطراری",cat:"emergency",machines:["Synergy","Infinity","Versa HD"],code:"EMG-006",duration:"اورژانسی",level:"متوسط",
 summary:"برخورد با قطع ناگهانی آب.",
 warn:"دستگاه بلافاصله خاموش شود.",
 tools:["ابزار قطع"],
 steps:[
   {t:"فشار Emergency Stop",level:"danger"},
   {t:"خاموشی سریع"},
   {t:"اطلاع به تیم فنی"},
   {t:"بررسی علت"},
   {t:"رفع مشکل"},
   {t:"پر کردن آب"},
   {t:"تست بدون Beam"},
   {t:"QA قبل از درمان"}
 ]},
{id:"em7",title:"Source Stuck پیشرفته (Brachy)",cat:"emergency",machines:["Flexitron"],code:"EMG-007",duration:"اورژانسی",level:"پیشرفته",
 summary:"برخورد با گیر کردن منبع در کانال.",
 warn:"هر ثانیه حیاتی. RSO مطلع شود.",
 tools:["Manual Retract","Survey Meter","دستکش سربی"],
 steps:[
   {t:"فشار Emergency Stop",level:"danger"},
   {t:"اطلاع فوری به RSO"},
   {t:"بررسی Position Indicator"},
   {t:"آماده‌سازی Retract Tool"},
   {t:"اجرای Manual Retract",level:"warn"},
   {t:"بررسی Safe با Survey Meter"},
   {t:"بازگشت بیمار"},
   {t:"ثبت در دفتر"},
   {t:"تماس با Elekta"}
 ]}
);

ERRORS.push(
{code:"MOT-001",sev:"orange",machine:"Synergy / Infinity",title:"Motor Overload — Gantry",act:"بررسی بار و دمای Motor"},
{code:"MOT-002",sev:"orange",machine:"Synergy / Infinity",title:"Motor Overload — Couch",act:"بررسی Load Cell"},
{code:"MOT-003",sev:"orange",machine:"همه Linacها",title:"Motor Overload — MLC",act:"تمیزکاری و بررسی Leaf"},
{code:"MOT-004",sev:"red",machine:"Synergy / Infinity",title:"Motor Drive Failure",act:"تعویض Motor Drive Board"},
{code:"MOT-005",sev:"red",machine:"Synergy / Infinity",title:"Resolver Error",act:"تعویض Resolver Board"},
{code:"MOT-006",sev:"orange",machine:"Infinity",title:"HexaPOD Motor Overload",act:"بررسی بار و Motor"},
{code:"SEN-001",sev:"orange",machine:"همه Linacها",title:"Temperature Sensor Failure",act:"تعویض یا کالیبراسیون"},
{code:"SEN-002",sev:"orange",machine:"Synergy / Infinity",title:"Pressure Sensor Error",act:"بررسی اتصالات"},
{code:"SEN-003",sev:"orange",machine:"همه Linacها",title:"Flow Sensor Low",act:"بررسی جریان آب"},
{code:"SEN-004",sev:"red",machine:"همه Linacها",title:"Radiation Monitor Fault",act:"کالیبراسیون یا تعویض"},
{code:"RF-101",sev:"red",machine:"Synergy / Infinity",title:"Filament Transformer Failure",act:"تعویض Transformer"},
{code:"RF-102",sev:"orange",machine:"Synergy / Infinity",title:"Bending Magnet Current Drift",act:"تنظیم جریان"},
{code:"RF-103",sev:"orange",machine:"همه Linacها",title:"Waveguide Flange Leak",act:"تعویض Flange و شارژ SF6"},
{code:"RF-104",sev:"red",machine:"همه Linacها",title:"Pulse Transformer Failure",act:"تعویض Pulse Transformer"},
{code:"RF-105",sev:"orange",machine:"Synergy / Infinity",title:"AFC Voltage Out of Range",act:"تنظیم AFC"},
{code:"RF-106",sev:"red",machine:"همه Linacها",title:"Klystron Overcurrent",act:"بررسی Filament و Beam"},
{code:"MEC-101",sev:"orange",machine:"Synergy / Infinity",title:"Couch Backlash Over Limit",act:"تنظیم Backlash"},
{code:"MEC-102",sev:"red",machine:"Synergy / Infinity",title:"Collimator Belt Broken",act:"تعویض Belt Drive"},
{code:"MEC-103",sev:"orange",machine:"همه Linacها",title:"Gantry Balance Warning",act:"تنظیم تعادل"},
{code:"MEC-104",sev:"orange",machine:"همه Linacها",title:"Chain Tension Low",act:"تنظیم کشش"},
{code:"MEC-105",sev:"red",machine:"Synergy",title:"Backup Chain Failure",act:"تعویض زنجیر"},
{code:"ELC-101",sev:"red",machine:"همه Linacها",title:"Motor Drive Board Failure",act:"تعویض برد"},
{code:"ELC-102",sev:"red",machine:"Synergy / Infinity",title:"Resolver Board Failure",act:"تعویض برد"},
{code:"ELC-103",sev:"orange",machine:"همه Linacها",title:"Voltage Regulator Drift",act:"کالیبراسیون یا تعویض"},
{code:"ELC-104",sev:"red",machine:"همه Linacها",title:"HV Board Failure",act:"تعویض برد HV"},
{code:"ELC-105",sev:"orange",machine:"Synergy / Infinity",title:"Serial Communication Error",act:"بررسی RS-232"},
{code:"SW-101",sev:"red",machine:"همه Linacها",title:"Database Corruption",act:"Repair یا Restore"},
{code:"SW-102",sev:"orange",machine:"همه Linacها",title:"Auto Backup Failed",act:"بررسی دیسک"},
{code:"SW-103",sev:"orange",machine:"همه Linacها",title:"DICOM Server Down",act:"ری‌استارت"},
{code:"SW-104",sev:"red",machine:"همه Linacها",title:"Critical Config Missing",act:"Restore از Backup"},
{code:"SW-105",sev:"orange",machine:"Infinity",title:"Integrity Update Failed",act:"نصب مجدد"},
{code:"SAFE-101",sev:"red",machine:"همه Linacها",title:"Coolant Flow Emergency",act:"خاموشی و بررسی پمپ"},
{code:"SAFE-102",sev:"red",machine:"همه Linacها",title:"Fire Alarm Active",act:"تخلیه و خاموشی"},
{code:"SAFE-103",sev:"red",machine:"Flexitron",title:"Source Stuck Critical",act:"Manual Retract"}
);

console.log("✅ data4.js — Added " + 30 + " manuals, " + 34 + " errors");