/* ═══════════════════════════════════════
   data.js — نسخه ۴.۰ (سرویس‌محور)
   تمرکز: تعمیر، عیب‌یابی، تعویض قطعات
   ═══════════════════════════════════════ */

const CATS = [
  {id:"replace",   name:"تعویض قطعات",     c1:"#FF3B30", c2:"#AF52DE", icon:"wrench"},
  {id:"trouble",   name:"عیب‌یابی",        c1:"#FF9500", c2:"#FF3B30", icon:"warn"},
  {id:"synergy",   name:"Synergy",         c1:"#5E5CE6", c2:"#3634A3", icon:"star"},
  {id:"infinity",  name:"Infinity",        c1:"#FF6482", c2:"#D30F45", icon:"star"},
  {id:"rf",        name:"RF و Waveguide",  c1:"#FF2D55", c2:"#AF52DE", icon:"target"},
  {id:"electronic",name:"الکترونیک و برد", c1:"#FFD60A", c2:"#FF9500", icon:"grid"},
  {id:"mech",      name:"مکانیک و میز",    c1:"#BF5AF2", c2:"#5856D6", icon:"wrench"},
  {id:"software",  name:"نرم‌افزار",       c1:"#64D2FF", c2:"#0A84FF", icon:"grid"},
  {id:"emergency", name:"اضطراری و ایمنی", c1:"#FF453A", c2:"#D70015", icon:"warn"},
  {id:"inventory", name:"انبار و قطعات",   c1:"#32D74B", c2:"#248A3D", icon:"check"},
  {id:"mlc",       name:"MLC و کولیما",    c1:"#FF375F", c2:"#AF52DE", icon:"grid"},
  {id:"pm",        name:"PM و نگهداری",    c1:"#00C7BE", c2:"#30B0C7", icon:"cal"}
];

const MANUALS = [

/* ════════ تعویض قطعات ════════ */
{id:"r1",title:"تعویض Magnetron",cat:"replace",machines:["Synergy","Infinity","Versa HD","Precise"],code:"REP-500",duration:"۳–۴ ساعت",level:"پیشرفته",
 summary:"رویه کامل تعویض Magnetron و بازگرداندن سیستم RF به عملکرد نرمال.",
 warn:"قبل از شروع، دستگاه را حداقل ۲ ساعت خاموش و بریکر را قطع کنید. تخلیه خازن‌ها الزامی است.",
 tools:["دستکش ESD","آچار تورک","فیلر","گریس وکیوم","چک‌لیست Elekta"],
 steps:[
   {t:"خاموشی کامل، قطع بریکر، انتظار ۳۰ دقیقه",level:"danger",note:"مرگ‌بار در صورت عدم رعایت"},
   {t:"باز کردن پنل Modulator و برچسب‌گذاری کابل‌ها"},
   {t:"جدا کردن کابل‌های HV، Heater و Filament"},
   {t:"باز کردن پیچ‌ها با تورک ۲۵ N·m"},
   {t:"برداشتن Magnetron قدیمی و بازرسی Waveguide",level:"warn",note:"در صورت کربن‌زدگی، Waveguide رو تمیز کن"},
   {t:"نصب Magnetron جدید با گریس وکیوم روی اورینگ‌ها"},
   {t:"اتصال کابل‌ها طبق برچسب‌ها و بستن پنل"},
   {t:"اجرای Auto-Conditioning (۳۰–۶۰ دقیقه)"},
   {t:"تنظیم AFC و بررسی پایداری Beam",level:"warn"},
   {t:"اجرای QA نهایی و تست خروجی"}
 ]},
{id:"r2",title:"تعویض Klystron",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-510",duration:"۴–۶ ساعت",level:"پیشرفته",
 summary:"تعویض کامل Klystron، تنظیم RF Drive و بازگرداندن به عملکرد نرمال.",
 warn:"تخلیه خازن‌های HV الزامی است. Klystron حدود ۵۰ کیلوگرم وزن دارد — از جرثقیل استفاده کنید.",
 tools:["دستکش عایق HV","آچار تورک","مولتی‌متر HV","جرثقیل کوچک"],
 steps:[
   {t:"خاموشی کامل و قطع بریکر اصلی",level:"danger"},
   {t:"انتظار ۳۰ دقیقه برای تخلیه کامل"},
   {t:"باز کردن پنل و برچسب‌گذاری کابل‌های HV، Filament، Heater و RF"},
   {t:"باز کردن پیچ‌ها با تورک ۳۰ N·m"},
   {t:"خارج کردن Klystron با جرثقیل",level:"warn"},
   {t:"بررسی Waveguide و تمیزکاری در صورت نیاز"},
   {t:"نصب Klystron جدید با اورینگ‌های نو"},
   {t:"اجرای Auto-Conditioning (۶۰–۹۰ دقیقه)"},
   {t:"تنظیم RF Drive و AFC",level:"warn"},
   {t:"کالیبراسیون و QA نهایی"}
 ]},
{id:"r3",title:"تعویض Target (آند تنگستنی)",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-520",duration:"۴ ساعت",level:"پیشرفته",
 summary:"تعویض Target پس از ۴–۵ سال یا در اثر فرسودگی.",
 warn:"دستگاه باید کاملاً سرد شود. قطع آب خنک‌کننده ممکن است نشتی ایجاد کند.",
 tools:["دستکش نسوز","آچار تورک","فیلر","گریس وکیوم","دستمال مخصوص"],
 steps:[
   {t:"خاموشی کامل و انتظار ۲ ساعت برای سرد شدن",level:"danger"},
   {t:"قطع بریکر اصلی و تخلیه خازن‌ها"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن اتصالات آب خنک‌کننده",note:"از ریختن آب روی قطعات جلوگیری کن"},
   {t:"باز کردن پیچ‌های Target با تورک"},
   {t:"خارج کردن Target قدیمی و بازرسی مسیر الکترون"},
   {t:"نصب Target جدید با گریس وکیوم"},
   {t:"اتصال مجدد آب و تست نشتی"},
   {t:"Auto-Conditioning (حداقل ۱ ساعت)"},
   {t:"کالیبراسیون کامل دز و QA"}
 ]},
{id:"r4",title:"تعویض Circulator",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-530",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض Circulator که وظیفه جداسازی RF بین Magnetron و Waveguide را دارد.",
 warn:"قبل از کار، فشار SF6 رو تخلیه کنید.",
 tools:["آچار تورک","فیلر","Frekvenz Meter"],
 steps:[
   {t:"خاموشی و قطع برق"},
   {t:"تخلیه فشار SF6 از Waveguide"},
   {t:"جدا کردن اتصالات Waveguide از دو طرف"},
   {t:"باز کردن پیچ‌های نگه‌دارنده"},
   {t:"خارج کردن Circulator قدیمی و بررسی بار داخلی"},
   {t:"نصب Circulator جدید با اورینگ‌های نو"},
   {t:"اتصال مجدد و شارژ SF6"},
   {t:"اجرای تست نشتی فشار"},
   {t:"تنظیم AFC و بررسی خروجی RF"},
   {t:"QA نهایی"}
 ]},
{id:"r5",title:"تعویض اتاقک یونیزاسیون مانیتور",cat:"replace",machines:["Synergy","Infinity","Versa HD"],code:"REP-505",duration:"۲ ساعت",level:"متوسط",
 summary:"تعویض Transmission Chamber در مسیر پرتو.",
 warn:"پس از تعویض، کالیبراسیون مجدد دز الزامی است.",
 tools:["پیچ‌گوشتی Torx","دستکش","فیلر"],
 steps:[
   {t:"خاموشی و سرد شدن"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن کابل HV و سیگنال"},
   {t:"باز کردن پیچ‌ها"},
   {t:"خارج کردن اتاقک قدیمی"},
   {t:"نصب اتاقک جدید با تنظیم دقیق موقعیت",level:"warn"},
   {t:"اتصال و بستن پنل"},
   {t:"اجرای Daily QA و کالیبراسیون مجدد"}
 ]},
{id:"r6",title:"تعویض Encoder Gantry",cat:"replace",machines:["Synergy","Infinity"],code:"REP-540",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض Encoder چرخش Gantry که دقت موقعیت‌یابی رو حفظ می‌کند.",
 tools:["آچار مخصوص","مولتی‌متر","فیلر دقیق"],
 steps:[
   {t:"خاموشی و قفل مکانیکی Gantry"},
   {t:"دسترسی به Encoder از پشت پنل"},
   {t:"جدا کردن کابل‌های Encoder"},
   {t:"باز کردن پیچ‌های نگه‌دارنده"},
   {t:"نصب Encoder جدید و تنظیم موقعیت صفر",level:"warn"},
   {t:"اتصال کابل‌ها"},
   {t:"کالیبراسیون Gantry Angle"},
   {t:"اجرای Star Shot برای تأیید"}
 ]},
{id:"r7",title:"تعویض Jaw Assembly",cat:"replace",machines:["Synergy","Infinity"],code:"REP-550",duration:"۴ ساعت",level:"پیشرفته",
 summary:"تعویض کامل Assembly Jaw X یا Y شامل Motor و Encoder.",
 tools:["آچار تورک","فیلر","نرم‌افزار Service"],
 steps:[
   {t:"خاموشی دستگاه"},
   {t:"باز کردن پنل Collimator"},
   {t:"جدا کردن Motor و Encoder کابل‌ها"},
   {t:"باز کردن پیچ‌های Assembly"},
   {t:"خارج کردن Assembly قدیمی"},
   {t:"نصب Assembly جدید و اتصال کابل‌ها"},
   {t:"اجرای کالیبراسیون Jaw"},
   {t:"تست Star Shot"}
 ]},

/* ════════ عیب‌یابی ════════ */
{id:"t1",title:"عیب‌یابی توقف پرتو در حین درمان",cat:"trouble",machines:["Synergy","Infinity","Versa HD","Unity"],code:"TRB-600",duration:"متغیر",level:"متوسط",
 summary:"راهنمای گام‌به‌گام عیب‌یابی توقف ناگهانی Beam در میانه درمان.",
 warn:"بیمار باید از اتاق خارج و دز اعمال‌شده ثبت شود.",
 tools:["دفتر خطا","لاگ سیستم","مولتی‌متر"],
 steps:[
   {t:"ثبت کد خطا از پنل Service"},
   {t:"بازبینی Service → Logs"},
   {t:"بررسی سطح آب خنک‌کننده",note:"دمای ورودی زیر ۳۰°C"},
   {t:"بررسی فشار SF6",level:"warn",note:"بالای ۲۸ psi"},
   {t:"بررسی AFC و وضعیت Magnetron/Klystron"},
   {t:"گزارش به Elekta اگر خطا تکرار شد"},
   {t:"اجرای QA روزانه قبل از ادامه درمان",level:"warn"}
 ]},
{id:"t2",title:"عیب‌یابی خطاهای MLC",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-610",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"رفع خطاهای گیرکردن Leaf، Motor و Encoder.",
 warn:"قبل از دسترسی دستی، MLC رو Home کنید.",
 tools:["برس نرم","هوای فشرده خشک","گریس MLC Original"],
 steps:[
   {t:"شناسایی شماره Leaf مشکل‌دار از Log"},
   {t:"اجرای Auto-Home"},
   {t:"بررسی مسیر Leaf برای آلودگی"},
   {t:"تمیزکاری ریل با برس نرم",level:"warn",note:"بدون حلال قوی"},
   {t:"بررسی Motor Leaf"},
   {t:"بازبینی Encoder در صورت تکرار"},
   {t:"اجرای Picket Fence پس از رفع"}
 ]},
{id:"t3",title:"عیب‌یابی سیستم خنک‌کننده",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-620",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"رفع مشکلات Chiller، پمپ، رادیاتور و افت فشار.",
 warn:"قبل از باز کردن، فشار رو تخلیه کنید.",
 tools:["مولتی‌متر","متر دما","فشارسنج"],
 steps:[
   {t:"بررسی سطح مایع و علائم نشتی"},
   {t:"اندازه‌گیری ΔT ورودی/خروجی",note:"۳–۵°C نرمال"},
   {t:"بررسی پمپ و جریان آب"},
   {t:"بازبینی فیلترها و رادیاتور"},
   {t:"تست سنسور دما و اینترلاک فشار"},
   {t:"تعویض مایع خنک‌کننده در صورت نیاز"},
   {t:"QA پس از رفع"}
 ]},
{id:"t4",title:"عیب‌یابی خطای Gantry Interlock (i70)",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-630",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"رفع خطای i70 که در Encoder یا Motor Gantry رخ می‌دهد.",
 warn:"قبل از بررسی، Gantry رو Home کنید.",
 tools:["مولتی‌متر","چک‌لیست Encoder"],
 steps:[
   {t:"ثبت کد دقیق"},
   {t:"بررسی Service Logs"},
   {t:"اجرای Reset Motors"},
   {t:"بررسی اتصال Encoder",level:"warn"},
   {t:"اندازه‌گیری ولتاژ Encoder (۵–۲۴V)"},
   {t:"بررسی Motor در حرکت آهسته"},
   {t:"کالیبراسیون Gantry Angle در صورت تکرار"},
   {t:"QA روزانه پس از رفع"}
 ]},
{id:"t5",title:"عیب‌یابی خطای Collimator Rotation",cat:"trouble",machines:["Synergy","Infinity"],code:"TRB-640",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"رفع خطای چرخش کولیما در اثر Encoder یا Motor Rotation.",
 tools:["مولتی‌متر","آچار تنظیم"],
 steps:[
   {t:"بررسی کد خطا در Log"},
   {t:"اجرای Reset برای Collimator"},
   {t:"بررسی اتصال Encoder Rotation"},
   {t:"تست حرکت چرخش ۳۶۰ درجه"},
   {t:"اندازه‌گیری موقعیت صفر"},
   {t:"کالیبراسیون Collimator Rotation"},
   {t:"Star Shot پس از رفع",level:"warn"}
 ]},
{id:"t6",title:"عیب‌یابی خطای Couch Position",cat:"trouble",machines:["Synergy","Infinity"],code:"TRB-650",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"خطای موقعیت میز — بررسی Encoder، Motor و مکانیک.",
 tools:["مولتی‌متر","فیلر"],
 steps:[
   {t:"بررسی کد خطا"},
   {t:"تست حرکت در همه محورها"},
   {t:"بررسی Encoder هر محور"},
   {t:"اندازه‌گیری دقت موقعیت با فانتوم"},
   {t:"کالیبراسیون محور مشکل‌دار",level:"warn"},
   {t:"تست Load Tolerance با وزن ۱۵۰kg"},
   {t:"QA نهایی"}
 ]},
{id:"t7",title:"عیب‌یابی فشار SF6 پایین",cat:"trouble",machines:["Synergy","Infinity"],code:"TRB-660",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"رفع افت فشار SF6 در Waveguide که باعث خطای Magnetron می‌شود.",
 warn:"شارژ SF6 باید با گاز خلوص ۹۹.۹۹٪ انجام شود.",
 tools:["سیلندر SF6","رگولاتور","Detector نشتی"],
 steps:[
   {t:"اندازه‌گیری فشار فعلی"},
   {t:"بررسی نشتی با Detector در کل مسیر"},
   {t:"تعویض اورینگ‌های مشکل‌دار"},
   {t:"شارژ SF6 تا ۳۰ psi",level:"warn"},
   {t:"تست نشتی ۲۴ ساعته"},
   {t:"بررسی پایداری پس از ۴۸ ساعت"},
   {t:"QA RF و دزیمتری"}
 ]},
{id:"t8",title:"عیب‌یابی خطای Modulator",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-670",duration:"۲ ساعت",level:"پیشرفته",
 summary:"رفع خطاهای Modulator شامل PFN، SCR و Pulse Transformer.",
 warn:"ولتاژهای HV خطرناک هستند. تخلیه کامل انجام شود.",
 tools:["مولتی‌متر HV","اسکوپ","دستکش عایق"],
 steps:[
   {t:"خاموشی و تخلیه خازن‌ها",level:"danger"},
   {t:"بررسی PFN و خازن‌ها"},
   {t:"تست SCR با مولتی‌متر"},
   {t:"بررسی Pulse Transformer"},
   {t:"تست فرم Pulse با اسکوپ"},
   {t:"تعویض قطعه معیوب"},
   {t:"اجرای QA و تست پایداری"}
 ]},
{id:"t9",title:"عیب‌یابی خطای Imaging kV",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-680",duration:"۹۰ دقیقه",level:"متوسط",
 summary:"رفع خطاهای سیستم تصویربرداری kV شامل Detector، Generator و کالیبراسیون.",
 tools:["مولتی‌متر kV","فانتوم هم‌ترازی"],
 steps:[
   {t:"ثبت کد خطا"},
   {t:"بررسی Generator kV"},
   {t:"بررسی Flat Panel Detector"},
   {t:"بررسی اتصالات کابل"},
   {t:"اجرای کالیبراسیون Dark و Gain"},
   {t:"تست کیفیت تصویر"},
   {t:"ثبت نتایج"}
 ]},
{id:"t10",title:"عیب‌یابی خطای ارتباط کنسول",cat:"trouble",machines:["Synergy","Infinity","Versa HD"],code:"TRB-690",duration:"۳۰ دقیقه",level:"متوسط",
 summary:"قطع ارتباط بین کنسول و دستگاه یا سرور.",
 tools:["مولتی‌متر شبکه","کابل تست"],
 steps:[
   {t:"بررسی کابل شبکه"},
   {t:"Ping بین کنسول و دستگاه"},
   {t:"بررسی IP و Subnet"},
   {t:"ری‌استارت سرویس ارتباطی"},
   {t:"بررسی فایروال"},
   {t:"تست DICOM Echo"},
   {t:"ثبت نتایج"}
 ]},

/* ════════ Synergy اختصاصی ════════ */
{id:"s1",title:"کالیبراسیون MLCi2 سیستم Synergy",cat:"synergy",machines:["Synergy"],code:"SYN-MLC-01",duration:"۲.۵ ساعت",level:"پیشرفته",
 summary:"کالیبراسیون کامل MLCi2 شامل تنظیم صفر مکانیکی، کالیبراسیون Encoder و بررسی Backlash هر Leaf.",
 warn:"قبل از شروع، MLC رو در Home قرار دهید و از تنظیمات فعلی Backup بگیرید.",
 tools:["فانتوم Picket Fence","فیلم EBT3","آچار تنظیم MLC","نرم‌افزار MLC Service"],
 steps:[
   {t:"ورود به Service Mode → MLC → Calibration"},
   {t:"اجرای Auto-Home و ثبت موقعیت صفر (۸۰ Leaf)"},
   {t:"تنظیم مکانیکی Leaf 1 و Leaf 80",level:"warn"},
   {t:"کالیبراسیون Encoder با تست حرکت تکی"},
   {t:"تست Backlash",note:"مقدار مجاز زیر ۰.۳mm"},
   {t:"اجرای Picket Fence با فیلم EBT3"},
   {t:"تحلیل فیلم و اعمال اصلاحات"},
   {t:"تست IMRT با Matrixx",level:"warn",note:"انحراف مجاز ۳٪ / ۳mm"},
   {t:"ذخیره کالیبراسیون و QA نهایی"}
 ]},
{id:"s2",title:"تعویض Motor Leaf MLCi2",cat:"synergy",machines:["Synergy"],code:"SYN-MLC-02",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض موتور یک Leaf از MLCi2 که معمولاً به دلیل خطای موقعیت یا صدای غیرعادی انجام می‌شود.",
 warn:"قبل از شروع، برق درایو MLC رو قطع کنید.",
 tools:["دستکش ESD","پیچ‌گوشتی Torx T10","آچار ۵.۵","گریس MLC Original Elekta"],
 steps:[
   {t:"خاموشی سیستم MLC و باز کردن پنل بالا"},
   {t:"برچسب‌گذاری کابل‌های Motor و Encoder"},
   {t:"جدا کردن کابل‌ها و باز کردن پیچ‌ها (۴ عدد T10)"},
   {t:"خارج کردن Motor و بررسی چرخ‌دنده"},
   {t:"نصب Motor جدید و اتصال کابل‌ها"},
   {t:"اجرای Auto-Home و کالیبراسیون Leaf"},
   {t:"تست عملکرد در کل رنج حرکت"},
   {t:"Picket Fence برای تأیید"}
 ]},
{id:"s3",title:"عیب‌یابی خطای Motor Current MLCi2",cat:"synergy",machines:["Synergy"],code:"SYN-TRB-01",duration:"۱ ساعت",level:"متوسط",
 summary:"خطای Motor Current Overload در MLCi2 در اثر آلودگی ریل، گریس خشک یا Motor معیوب.",
 warn:"هرگز با اعمال دستی روی Leaf، حرکت رو اجبار نکنید.",
 tools:["برس نرم","هوای فشرده خشک","گریس MLC"],
 steps:[
   {t:"ثبت شماره Leaf دارای خطا از Service Log"},
   {t:"اجرای Auto-Home"},
   {t:"بررسی مسیر حرکت Leaf"},
   {t:"تمیزکاری ریل با برس نرم",level:"warn"},
   {t:"بررسی و گریس‌کاری مجدد ریل"},
   {t:"تست جریان Motor با نرم‌افزار Service"},
   {t:"Picket Fence پس از رفع"},
   {t:"تعویض Motor در صورت تکرار"}
 ]},
{id:"s4",title:"تنظیم Magnetron Synergy",cat:"synergy",machines:["Synergy"],code:"SYN-RF-01",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تنظیم دقیق AFC، فرکانس و توان خروجی Magnetron پس از تعویض یا افت توان.",
 warn:"کار با High Voltage خطرناک است.",
 tools:["مولتی‌متر HV","Frekvenz Meter","نرم‌افزار Service"],
 steps:[
   {t:"Warm-up کامل دستگاه (۲۰ دقیقه)"},
   {t:"ورود به Service Mode → RF System"},
   {t:"بررسی فرکانس پایه (~۲۸۵۶ MHz)"},
   {t:"بررسی AFC Voltage در Standby"},
   {t:"تنظیم AFC در حین تابش"},
   {t:"اندازه‌گیری توان خروجی (۵.۵ MW)",level:"warn"},
   {t:"تنظیم محفظه در صورت نیاز"},
   {t:"Auto-Conditioning و بررسی پایداری"},
   {t:"QA دزیمتری پس از تنظیم"}
 ]},
{id:"s5",title:"تعویض Target Synergy",cat:"synergy",machines:["Synergy"],code:"SYN-REP-01",duration:"۴ ساعت",level:"پیشرفته",
 summary:"تعویض Target در Synergy پس از ۴–۵ سال یا فرسودگی.",
 warn:"دستگاه باید کاملاً سرد شود و بریکر قطع گردد.",
 tools:["دستکش نسوز","آچار تورک","فیلر","گریس وکیوم"],
 steps:[
   {t:"خاموشی کامل و انتظار ۲ ساعت",level:"danger"},
   {t:"قطع بریکر و تخلیه خازن‌ها"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن اتصالات آب خنک‌کننده"},
   {t:"باز کردن پیچ‌های Target"},
   {t:"خارج کردن Target قدیمی"},
   {t:"نصب Target جدید"},
   {t:"اتصال آب و تست نشتی"},
   {t:"Auto-Conditioning (حداقل ۱ ساعت)"},
   {t:"کالیبراسیون دز و QA"}
 ]},
{id:"s6",title:"تعویض Circulator Synergy",cat:"synergy",machines:["Synergy"],code:"SYN-REP-02",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض Circulator در Synergy.",
 warn:"قبل از کار، فشار SF6 رو تخلیه کنید.",
 tools:["آچار تورک","فیلر","Frekvenz Meter"],
 steps:[
   {t:"خاموشی و قطع برق"},
   {t:"تخلیه فشار SF6"},
   {t:"جدا کردن اتصالات Waveguide"},
   {t:"باز کردن پیچ‌های نگه‌دارنده"},
   {t:"خارج کردن Circulator قدیمی"},
   {t:"نصب Circulator جدید"},
   {t:"شارژ SF6 و تست نشتی"},
   {t:"تنظیم AFC"},
   {t:"QA نهایی"}
 ]},

/* ════════ Infinity اختصاصی ════════ */
{id:"i1",title:"کالیبراسیون Agility MLC (Infinity)",cat:"infinity",machines:["Infinity"],code:"INF-MLC-01",duration:"۳ ساعت",level:"پیشرفته",
 summary:"کالیبراسیون کامل Agility MLC با ۱۶۰ Leaf شامل Backlash، Gain و موقعیت مطلق.",
 warn:"Agility حساس‌تر از MLCi2 است — دقت حیاتی است.",
 tools:["فانتوم Picket Fence","فیلم EBT3","نرم‌افزار Agility Service"],
 steps:[
   {t:"ورود به Service Mode → Agility → Calibration"},
   {t:"اجرای Auto-Home و ثبت صفر هر ۱۶۰ Leaf"},
   {t:"کالیبراسیون Backlash بانک A"},
   {t:"کالیبراسیون Backlash بانک B"},
   {t:"تنظیم Gain هر Leaf",note:"انحراف مجاز زیر ۰.۲mm"},
   {t:"تست Picket Fence با تحلیل نرم‌افزاری",level:"warn"},
   {t:"تست IMRT با ۱۱ میدان"},
   {t:"VMAT QA با ArcCHECK"},
   {t:"Backup کالیبراسیون"}
 ]},
{id:"i2",title:"QA ماهانه Agility — Garden Fence",cat:"infinity",machines:["Infinity"],code:"INF-MLC-02",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"تست ماهانه Agility MLC با Garden Fence برای بررسی هر ۱۶۰ Leaf.",
 tools:["فیلم EBT3","اسکنر فیلم","FilmQA Pro"],
 steps:[
   {t:"تنظیم فانتوم در Isocenter با لیزر"},
   {t:"اجرای فایل Garden Fence"},
   {t:"تابش با ۶ MV و ۵۰۰ MU"},
   {t:"Development و اسکن با ۳۰۰ DPI"},
   {t:"تحلیل با FilmQA Pro",level:"warn",note:"انحراف مجاز زیر ۱mm"},
   {t:"ثبت در فرم QA"},
   {t:"کالیبراسیون MLC در صورت انحراف"}
 ]},
{id:"i3",title:"QA روزانه Integrity — Infinity",cat:"infinity",machines:["Infinity"],code:"INF-QA-01",duration:"۲۰ دقیقه",level:"پایه",
 summary:"چک‌لیست روزانه سیستم Integrity شامل بررسی Status، خطاها و عملکرد کلی.",
 tools:["چک‌لیست روزانه"],
 steps:[
   {t:"بررسی سبز بودن پس‌زمینه Integrity"},
   {t:"بررسی Status Bar برای هشدارها"},
   {t:"ورود به Admin → System Health"},
   {t:"بررسی لاگ خطاهای ۲۴ ساعت گذشته"},
   {t:"بررسی فضای دیسک (حداقل ۲۰٪ آزاد)"},
   {t:"تست ارتباط با ARIA/MOSAIQ"},
   {t:"بررسی سینک زمان سیستم"},
   {t:"شروع QA روزانه دزیمتری"}
 ]},
{id:"i4",title:"تعویض Agility MLC Bank",cat:"infinity",machines:["Infinity"],code:"INF-REP-01",duration:"۸ ساعت",level:"پیشرفته",
 summary:"تعویض کامل یک Bank از Agility MLC (۸۰ Leaf) پس از آسیب یا ۱۰ سال کار.",
 warn:"این رویه تخصصی است — هماهنگی با Elekta Service الزامی است.",
 tools:["کیت تعویض Agility","آچار تورک","جرثقیل کوچک"],
 steps:[
   {t:"Backup کامل از تنظیمات MLC"},
   {t:"خاموشی و قطع برق MLC"},
   {t:"باز کردن پنل Head"},
   {t:"جدا کردن کابل‌ها (۸۰×۲ کابل)",note:"از همه عکس بگیرید"},
   {t:"باز کردن پیچ‌های Bank"},
   {t:"خارج کردن Bank با جرثقیل",level:"warn"},
   {t:"نصب Bank جدید و اتصال کابل‌ها"},
   {t:"Auto-Home و کالیبراسیون کامل"},
   {t:"Picket Fence و Garden Fence",level:"warn"},
   {t:"VMAT QA با فانتوم"}
 ]},
{id:"i5",title:"کالیبراسیون HexaPOD Couch",cat:"infinity",machines:["Infinity"],code:"INF-Couch-01",duration:"۳ ساعت",level:"پیشرفته",
 summary:"کالیبراسیون میز HexaPOD با ۶ درجه آزادی.",
 tools:["فانتوم هم‌ترازی","نرم‌افزار HexaPOD Service"],
 steps:[
   {t:"بررسی نصب فیزیکی و کابل‌ها"},
   {t:"Warm-up سیستم (۱۵ دقیقه)"},
   {t:"Service → HexaPOD → Calibration"},
   {t:"Auto-Home و بررسی موقعیت صفر"},
   {t:"کالیبراسیون Pitch، Roll، Yaw"},
   {t:"کالیبراسیون Translation در X، Y، Z"},
   {t:"تست دقت با فانتوم",note:"انحراف مجاز زیر ۱mm و ۱°"},
   {t:"اتصال به XVI و تست Workflow"}
 ]},
{id:"i6",title:"عیب‌یابی Agility Leaf Error",cat:"infinity",machines:["Infinity"],code:"INF-TRB-01",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"رفع خطای موقعیت یا Backlash در Leafهای Agility.",
 tools:["نرم‌افزار Service","برس نرم","گریس"],
 steps:[
   {t:"شناسایی Leaf مشکل‌دار از Log"},
   {t:"اجرای Auto-Home"},
   {t:"بررسی مسیر حرکت Leaf"},
   {t:"تمیزکاری و گریس‌کاری"},
   {t:"تست حرکت تکی Leaf"},
   {t:"بررسی Encoder و Motor"},
   {t:"اجرای Picket Fence"},
   {t:"تعویض Leaf در صورت تکرار"}
 ]},
{id:"i7",title:"تنظیم FFF Beam در Infinity",cat:"infinity",machines:["Infinity"],code:"INF-FFF-01",duration:"۴ ساعت",level:"پیشرفته",
 summary:"پیکربندی و کالیبراسیون پرتو FFF برای SBRT/SRS.",
 warn:"نیازمند مجوز فیزیک پزشکی و تست‌های دزیمتری گسترده.",
 tools:["فانتوم آب","اتاقک Farmer","PinPoint","Monaco"],
 steps:[
   {t:"بررسی نصب Hardware FFF"},
   {t:"Service → Beam Configuration"},
   {t:"فعال‌سازی ۶ MV FFF و ۱۰ MV FFF"},
   {t:"کالیبراسیون خروجی (Dose Rate بالای ۱۴۰۰ MU/min)"},
   {t:"اندازه‌گیری PDD و TPR"},
   {t:"Profile عرضی FFF"},
   {t:"مدل‌سازی در Monaco"},
   {t:"تست SBRT با فانتوم",note:"انحراف زیر ۳٪"}
 ]},

/* ════════ RF و Waveguide ════════ */
{id:"rf1",title:"تنظیم AFC و پایداری فرکانس",cat:"rf",machines:["Synergy","Infinity","Versa HD"],code:"RF-001",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"تنظیم AFC برای حفظ فرکانس Magnetron/Klystron روی ۲۸۵۶ MHz.",
 warn:"فرکانس باید دقیقاً تنظیم شود — انحراف باعث افت توان و خطا می‌شود.",
 tools:["Frekvenz Meter","مولتی‌متر HV","نرم‌افزار Service"],
 steps:[
   {t:"Warm-up کامل (۲۰ دقیقه)"},
   {t:"ورود به Service → RF System"},
   {t:"بررسی AFC Voltage در Standby"},
   {t:"تنظیم AFC در حین تابش"},
   {t:"بررسی فرکانس واقعی با Frekvenz Meter"},
   {t:"تنظیم محفظه Magnetron در صورت انحراف"},
   {t:"تست پایداری ۳۰ دقیقه"},
   {t:"QA RF پس از تنظیم"}
 ]},
{id:"rf2",title:"شارژ SF6 و تست نشتی",cat:"rf",machines:["Synergy","Infinity","Versa HD"],code:"RF-002",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"شارژ گاز SF6 در Waveguide و بررسی نشتی.",
 warn:"SF6 باید خلوص ۹۹.۹۹٪ داشته باشد. شارژ سریع می‌تواند باعث یخ‌زدگی شود.",
 tools:["سیلندر SF6","رگولاتور","Detector نشتی"],
 steps:[
   {t:"بررسی فشار فعلی"},
   {t:"جستجوی نشتی با Detector در کل مسیر"},
   {t:"تعویض اورینگ‌های مشکل‌دار"},
   {t:"شارژ تا فشار ۳۰ psi (آهسته)",level:"warn"},
   {t:"اجرای تست نشتی ۲۴ ساعته"},
   {t:"بررسی پایداری پس از ۴۸ ساعت"},
   {t:"QA RF و دزیمتری"}
 ]},
{id:"rf3",title:"تعویض Waveguide Section",cat:"rf",machines:["Synergy","Infinity"],code:"RF-003",duration:"۴ ساعت",level:"پیشرفته",
 summary:"تعویض بخش آسیب‌دیده Waveguide پس از Arc یا نشتی.",
 warn:"تخلیه SF6 قبل از کار. دقت در اتصالات و آب‌بندی الزامی است.",
 tools:["آچار تورک","فیلر","گریس وکیوم","کیت اورینگ"],
 steps:[
   {t:"خاموشی و تخلیه SF6"},
   {t:"برچسب‌گذاری اتصالات"},
   {t:"باز کردن پیچ‌های Flange"},
   {t:"خارج کردن بخش آسیب‌دیده"},
   {t:"بررسی و تمیزکاری سایر بخش‌ها"},
   {t:"نصب Waveguide جدید با اورینگ نو"},
   {t:"شارژ SF6"},
   {t:"تست نشتی ۲۴ ساعته"},
   {t:"Auto-Conditioning و QA"}
 ]},
{id:"rf4",title:"عیب‌یابی Arc Detector",cat:"rf",machines:["Synergy","Infinity"],code:"RF-TRB-01",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"رفع خطاهای Arc در Waveguide که معمولاً از رطوبت یا آلودگی است.",
 tools:["Detector نشتی","هوای خشک","دستمال مخصوص"],
 steps:[
   {t:"بررسی کد خطا در Log"},
   {t:"بررسی فشار SF6"},
   {t:"بررسی نشتی با Detector"},
   {t:"بررسی رطوبت در Waveguide"},
   {t:"تمیزکاری بخش‌های آسیب‌دیده"},
   {t:"اجرای Auto-Conditioning"},
   {t:"تست پایداری"}
 ]},
{id:"rf5",title:"بررسی و تنظیم Pulse Forming Network",cat:"rf",machines:["Synergy","Infinity","Versa HD"],code:"RF-004",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تنظیم PFN برای تولید Pulse صحیح در Modulator.",
 warn:"ولتاژهای HV خطرناک هستند.",
 tools:["اسکوپ","مولتی‌متر HV","دستکش عایق"],
 steps:[
   {t:"خاموشی و تخلیه خازن‌ها",level:"danger"},
   {t:"بررسی خازن‌های PFN"},
   {t:"بررسی سلف‌ها"},
   {t:"تست Pulse با اسکوپ"},
   {t:"تنظیم در صورت انحراف"},
   {t:"روشن کردن و بررسی پایداری"},
   {t:"QA نهایی"}
 ]},

/* ════════ الکترونیک و برد ════════ */
{id:"e1",title:"تعویض Modulator Board",cat:"electronic",machines:["Synergy","Infinity"],code:"ELC-001",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض برد Modulator که وظیفه تولید Pulse HV را دارد.",
 warn:"تخلیه کامل خازن‌ها قبل از شروع الزامی است.",
 tools:["دستکش ESD","پیچ‌گوشتی Torx","مولتی‌متر"],
 steps:[
   {t:"خاموشی کامل و تخلیه خازن‌ها",level:"danger"},
   {t:"باز کردن پنل و برچسب‌گذاری کابل‌ها"},
   {t:"عکس گرفتن از اتصالات"},
   {t:"جدا کردن کابل‌ها"},
   {t:"باز کردن پیچ‌های برد"},
   {t:"نصب برد جدید"},
   {t:"اتصال طبق برچسب‌ها"},
   {t:"روشن کردن و بررسی اولیه"},
   {t:"تنظیم Pulse و QA"}
 ]},
{id:"e2",title:"تعویض Control Board",cat:"electronic",machines:["Synergy","Infinity","Versa HD"],code:"ELC-002",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تعویض برد Control اصلی دستگاه.",
 warn:"بعد از تعویض، ممکن است نیاز به بازیابی تنظیمات از Backup باشد.",
 tools:["دستکش ESD","پیچ‌گوشتی Torx"],
 steps:[
   {t:"Backup کامل از تنظیمات فعلی"},
   {t:"خاموشی و قطع برق"},
   {t:"باز کردن پنل"},
   {t:"جدا کردن کابل‌های برد"},
   {t:"تعویض برد"},
   {t:"اتصال کابل‌ها"},
   {t:"روشن کردن و بازیابی تنظیمات"},
   {t:"کالیبراسیون و تست کامل"}
 ]},
{id:"e3",title:"تعویض Encoder Board",cat:"electronic",machines:["Synergy","Infinity"],code:"ELC-003",duration:"۲ ساعت",level:"متوسط",
 summary:"تعویض برد Encoder در محورهای مختلف.",
 tools:["دستکش ESD","پیچ‌گوشتی"],
 steps:[
   {t:"خاموشی و قفل مکانیکی"},
   {t:"باز کردن پنل دسترسی"},
   {t:"جدا کردن کابل Encoder"},
   {t:"تعویض برد"},
   {t:"اتصال کابل"},
   {t:"کالیبراسیون محور مربوطه"},
   {t:"تست دقت موقعیت"}
 ]},
{id:"e4",title:"تعویض Power Supply اصلی",cat:"electronic",machines:["Synergy","Infinity","Versa HD"],code:"ELC-004",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تعویض منبع تغذیه اصلی یا ماژول‌های تغذیه.",
 warn:"قطع برق اصلی و تخلیه خازن‌ها الزامی است.",
 tools:["مولتی‌متر","پیچ‌گوشتی"],
 steps:[
   {t:"قطع برق اصلی"},
   {t:"باز کردن پنل"},
   {t:"اندازه‌گیری ولتاژهای خروجی (پیش از تعویض)"},
   {t:"جدا کردن کابل‌ها"},
   {t:"تعویض Power Supply"},
   {t:"اتصال مجدد"},
   {t:"اندازه‌گیری ولتاژهای خروجی"},
   {t:"تست کامل سیستم"}
 ]},
{id:"e5",title:"چک ولتاژهای تغذیه سیستم",cat:"electronic",machines:["Synergy","Infinity"],code:"ELC-005",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"اندازه‌گیری ولتاژهای مختلف تغذیه برای عیب‌یابی.",
 tools:["مولتی‌متر دقیق"],
 steps:[
   {t:"اندازه‌گیری ولتاژ ۲۴V"},
   {t:"اندازه‌گیری ولتاژ ۱۲V"},
   {t:"اندازه‌گیری ولتاژ ۵V"},
   {t:"اندازه‌گیری ولتاژ ۳.۳V"},
   {t:"بررسی Ripple با اسکوپ"},
   {t:"ثبت در فرم سرویس"}
 ]},

/* ════════ مکانیک و میز ════════ */
{id:"mec1",title:"روانکاری ریل‌های Gantry",cat:"mech",machines:["Synergy","Infinity","Versa HD"],code:"MEC-001",duration:"۹۰ دقیقه",level:"متوسط",
 summary:"روانکاری دوره‌ای ریل‌های چرخش Gantry.",
 warn:"فقط از گریس Original Elekta استفاده کن.",
 tools:["گریس Elekta","برس نرم","دستمال"],
 steps:[
   {t:"خاموشی و قفل مکانیکی Gantry"},
   {t:"دسترسی به ریل از پشت دستگاه"},
   {t:"تمیزکاری ریل با دستمال"},
   {t:"اعمال گریس یکنواخت"},
   {t:"چرخش دستی Gantry برای پخش گریس"},
   {t:"بررسی نبود صدای غیرعادی"},
   {t:"تست حرکت کامل"}
 ]},
{id:"mec2",title:"تعویض Motor Couch",cat:"mech",machines:["Synergy","Infinity"],code:"MEC-002",duration:"۳ ساعت",level:"پیشرفته",
 summary:"تعویض موتور محور Long، Lat یا Vert میز.",
 warn:"میز باید قفل و در موقعیت امن باشد.",
 tools:["آچار مخصوص","مولتی‌متر","چک‌لیست Motor"],
 steps:[
   {t:"خاموشی و قفل میز"},
   {t:"باز کردن پنل دسترسی"},
   {t:"جدا کردن کابل Motor"},
   {t:"باز کردن پیچ‌های نگه‌دارنده"},
   {t:"خارج کردن Motor قدیمی"},
   {t:"نصب Motor جدید"},
   {t:"اتصال کابل و تست"},
   {t:"کالیبراسیون محور"},
   {t:"تست Load Tolerance"}
 ]},
{id:"mec3",title:"تعویض Encoder Couch",cat:"mech",machines:["Synergy","Infinity"],code:"MEC-003",duration:"۲ ساعت",level:"متوسط",
 summary:"تعویض Encoder موقعیت میز.",
 tools:["آچار مخصوص","مولتی‌متر"],
 steps:[
   {t:"خاموشی و قفل میز"},
   {t:"دسترسی به Encoder"},
   {t:"جدا کردن کابل"},
   {t:"تعویض Encoder"},
   {t:"اتصال کابل"},
   {t:"کالیبراسیون محور"},
   {t:"تست دقت موقعیت"}
 ]},
{id:"mec4",title:"تنظیم Backlash Gantry",cat:"mech",machines:["Synergy","Infinity"],code:"MEC-004",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"تنظیم Backlash چرخش Gantry.",
 tools:["نرم‌افزار Service","مولتی‌متر"],
 steps:[
   {t:"اجرای تست Backlash در نرم‌افزار"},
   {t:"بررسی مقدار فعلی"},
   {t:"تنظیم در صورت انحراف"},
   {t:"تست مجدد پس از تنظیم"},
   {t:"کالیبراسیون Gantry Angle"},
   {t:"Star Shot برای تأیید"}
 ]},
{id:"mec5",title:"تعویض بلبرینگ Gantry",cat:"mech",machines:["Synergy","Infinity"],code:"MEC-005",duration:"۸ ساعت",level:"پیشرفته",
 summary:"تعویض بلبرینگ اصلی چرخش Gantry (رویه تخصصی).",
 warn:"نیازمند هماهنگی با Elekta Service و جرثقیل.",
 tools:["جرثقیل","کیت تعویض بلبرینگ","آچار تورک"],
 steps:[
   {t:"هماهنگی با Elekta Service"},
   {t:"Backup کامل"},
   {t:"خاموشی و قفل Gantry"},
   {t:"باز کردن پنل‌ها"},
   {t:"پشتیبانی Gantry با جرثقیل"},
   {t:"باز کردن بلبرینگ قدیمی"},
   {t:"نصب بلبرینگ جدید"},
   {t:"بستن و تست چرخش"},
   {t:"کالیبراسیون کامل"}
 ]},
{id:"mec6",title:"تنظیم HexaPOD Couch",cat:"mech",machines:["Infinity"],code:"MEC-006",duration:"۲ ساعت",level:"متوسط",
 summary:"تنظیم و کالیبراسیون میز HexaPOD با ۶DoF.",
 tools:["فانتوم هم‌ترازی","نرم‌افزار Service"],
 steps:[
   {t:"بررسی اتصالات"},
   {t:"Warm-up"},
   {t:"Auto-Home"},
   {t:"بررسی موقعیت صفر"},
   {t:"کالیبراسیون در ۶ جهت"},
   {t:"تست دقت"},
   {t:"تست Workflow با XVI"}
 ]},

/* ════════ نرم‌افزار ════════ */
{id:"sw1",title:"Backup و Restore تنظیمات سیستم",cat:"software",machines:["Synergy","Infinity","Versa HD"],code:"SW-001",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"پشتیبان‌گیری و بازیابی تنظیمات سیستم شامل Service Config و User Data.",
 warn:"Backup رو در جای امن نگهداری کن. بازیابی اشتباه می‌تواند تنظیمات رو از بین ببرد.",
 tools:["USB فرمت‌شده","دسترسی Admin"],
 steps:[
   {t:"ورود به سیستم به عنوان Administrator"},
   {t:"Service → Backup → Configuration"},
   {t:"انتخاب مقصد USB"},
   {t:"اجرای Backup و انتظار"},
   {t:"بررسی موفقیت از Log"},
   {t:"برچسب‌گذاری USB با تاریخ"},
   {t:"در صورت بازیابی: Service → Restore"},
   {t:"انتخاب فایل و تأیید"},
   {t:"ری‌استارت سیستم"}
 ]},
{id:"sw2",title:"نصب مجدد iGuide یا Integrity",cat:"software",machines:["Synergy","Infinity","Versa HD"],code:"SW-002",duration:"۴ ساعت",level:"پیشرفته",
 summary:"نصب مجدد نرم‌افزار اصلی پس از خرابی سیستم یا Corruption.",
 warn:"قبل از نصب، مطمئن شو نسخه نصب در دسترس است.",
 tools:["Media نصب","License","دسترسی Service"],
 steps:[
   {t:"Backup کامل از داده‌ها"},
   {t:"بررسی License"},
   {t:"بوت از Media نصب"},
   {t:"اجرای Wizard نصب"},
   {t:"پیکربندی اولیه"},
   {t:"بازیابی Backup"},
   {t:"تست سیستم"},
   {t:"کالیبراسیون‌های لازم"}
 ]},
{id:"sw3",title:"Recovery پس از Crash سیستم",cat:"software",machines:["Synergy","Infinity"],code:"SW-003",duration:"۹۰ دقیقه",level:"متوسط",
 summary:"بازگرداندن سیستم پس از Crash ناگهانی یا Blue Screen.",
 tools:["دسترسی Service","Backup اخیر"],
 steps:[
   {t:"ثبت زمان و شرایط Crash"},
   {t:"بررسی لاگ‌های Crash"},
   {t:"اجرای Recovery Mode"},
   {t:"بررسی دیسک و فایل‌سیستم"},
   {t:"بازیابی از Backup در صورت نیاز"},
   {t:"تست سیستم"},
   {t:"بررسی علت و پیشگیری"}
 ]},
{id:"sw4",title:"آپدیت نرم‌افزار",cat:"software",machines:["Synergy","Infinity","Versa HD"],code:"SW-004",duration:"۳ ساعت",level:"پیشرفته",
 summary:"آپدیت نرم‌افزار سیستم به نسخه جدید.",
 warn:"قبل از آپدیت، Backup کامل الزامی است. نسخه سازگاری را چک کن.",
 tools:["Media آپدیت","License جدید"],
 steps:[
   {t:"بررسی سازگاری نسخه"},
   {t:"Backup کامل"},
   {t:"بستن همه برنامه‌ها"},
   {t:"اجرای Wizard آپدیت"},
   {t:"انتظار برای تکمیل"},
   {t:"بررسی نسخه جدید"},
   {t:"تست سیستم"},
   {t:"اجرای QA نهایی"}
 ]},
{id:"sw5",title:"عیب‌یابی خطاهای سیستم Integrity",cat:"software",machines:["Infinity"],code:"SW-TRB-01",duration:"۶۰ دقیقه",level:"متوسط",
 summary:"رفع خطاهای متداول سیستم Integrity در Infinity.",
 tools:["دسترسی Admin","لاگ سیستم"],
 steps:[
   {t:"ثبت کد خطا"},
   {t:"بررسی System Health"},
   {t:"بررسی فضای دیسک"},
   {t:"بررسی سرویس‌های Windows"},
   {t:"ری‌استارت سرویس معیوب"},
   {t:"بررسی لاگ‌های Application"},
   {t:"تست عملکرد"}
 ]},

/* ════════ اضطراری و ایمنی ════════ */
{id:"em1",title:"Source Stuck در Brachytherapy",cat:"emergency",machines:["Flexitron"],code:"EMG-001",duration:"اورژانسی",level:"پیشرفته",
 summary:"بازگرداندن اضطراری منبع Ir-192 به Safe در صورت گیر کردن.",
 warn:"این رویه اورژانسی است. هر ثانیه حیاتی است.",
 tools:["ابزار Manual Retract","Survey Meter"],
 steps:[
   {t:"پress دکمه Emergency Stop",level:"danger"},
   {t:"اطلاع به RSO و تیم فیزیک"},
   {t:"بررسی Source Position Indicator"},
   {t:"استفاده از Manual Retract",level:"warn"},
   {t:"بررسی Safe با Survey Meter"},
   {t:"خروج بیمار در صورت نیاز"},
   {t:"ثبت در دفتر حادثه"},
   {t:"هماهنگی با Elekta Service"}
 ]},
{id:"em2",title:"خروج اضطراری بیمار",cat:"emergency",machines:["Synergy","Infinity","Versa HD","Unity"],code:"EMG-002",duration:"اورژانسی",level:"پایه",
 summary:"خروج سریع و ایمن بیمار در مواقع اضطراری.",
 warn:"در صورت اضطراری، اولویت با ایمنی بیمار است.",
 tools:["Emergency Stop","دستگیره درب"],
 steps:[
   {t:"فشار Emergency Stop روی پنل"},
   {t:"ورود به اتاق درمان"},
   {t:"آزاد کردن Couch و پایین آوردن به سطح امن"},
   {t:"کمک به بیمار برای بلند شدن"},
   {t:"راهنمایی بیمار به بیرون"},
   {t:"بررسی وضعیت بیمار"},
   {t:"ثبت در دفتر"},
   {t:"رفع علت اضطراری قبل از ادامه"}
 ]},
{id:"em3",title:"قطع برق ناگهانی",cat:"emergency",machines:["Synergy","Infinity","Versa HD"],code:"EMG-003",duration:"اورژانسی",level:"متوسط",
 summary:"رویه برخورد با قطع ناگهانی برق اصلی یا UPS.",
 tools:["چراغ قوه","لاگ UPS"],
 steps:[
   {t:"بررسی UPS در حال کار"},
   {t:"اطمینان از ایمنی بیمار"},
   {t:"بررسی علت قطع (داخل یا خارج)"},
   {t:"اعلام به برقکار و مدیر"},
   {t:"خاموش کردن ایمن سیستم"},
   {t:"پس از بازگشت برق: بررسی Load"},
   {t:"ری‌استارت تدریجی"},
   {t:"QA کامل قبل از ادامه"}
 ]},
{id:"em4",title:"آتش‌سوزی در اتاق درمان",cat:"emergency",machines:["همه"],code:"EMG-004",duration:"اورژانسی",level:"پایه",
 summary:"رویه برخورد با آتش‌سوزی در اتاق درمان.",
 warn:"هرگز با آتش الکتریکی با آب مقابله نکنید.",
 tools:["کپسول CO2","دستگیره درب"],
 steps:[
   {t:"فعال کردن سیستم اعلام حریق"},
   {t:"اطمینان از خروج بیمار"},
   {t:"قطع برق اصلی"},
   {t:"استفاده از کپسول CO2 (اگر ایمن است)"},
   {t:"تماس با آتش‌نشانی"},
   {t:"بستن درب اتاق"},
   {t:"اطلاع به تیم ایمنی"},
   {t:"عدم استفاده از دستگاه تا بررسی کامل"}
 ]},
{id:"em5",title:"خطاهای بحرانی دستگاه",cat:"emergency",machines:["همه"],code:"EMG-005",duration:"اورژانسی",level:"پیشرفته",
 summary:"لیست خطاهای بحرانی که نیاز به توقف فوری درمان دارند.",
 warn:"در صورت مشاهده این خطاها، درمان بلافاصله متوقف شود.",
 tools:["دفتر خطا"],
 steps:[
   {t:"بررسی خطاهای بحرانی: E-510 (عدم تطابق دز)"},
   {t:"بررسی E-605 (اینترلاک درب)"},
   {t:"بررسی E-410 (افت میدان مغناطیسی)"},
   {t:"بررسی E-115 (دمای Modulator)"},
   {t:"بررسی SYN-E03 (Waveguide Arc)"},
   {t:"توقف درمان و خروج بیمار"},
   {t:"اعلام به مسئول فنی"},
   {t:"رفع خطا قبل از ادامه"}
 ]},

/* ════════ انبار و قطعات ════════ */
{id:"inv1",title:"لیست قطعات مصرفی پرمصرف",cat:"inventory",machines:["همه"],code:"INV-001",duration:"مرجع",level:"پایه",
 summary:"لیست قطعات پرمصرف دستگاه‌های Linac و موجودی پیشنهادی.",
 tools:["لیست مرجع"],
 steps:[
   {t:"Magnetron MG6026 — موجودی حداقل ۱"},
   {t:"Klystron 5MW — موجودی حداقل ۱"},
   {t:"MLC Motor Leaf — موجودی حداقل ۵"},
   {t:"MLC Encoder — موجودی حداقل ۲"},
   {t:"Ion Chamber — موجودی حداقل ۲"},
   {t:"Target Tungsten — موجودی حداقل ۱"},
   {t:"SF6 Gas — موجودی ۱ سیلندر"},
   {t:"Coolant Elekta — موجودی ۲۰ لیتر"},
   {t:"MLC Grease — موجودی ۲ تیوب"},
   {t:"O-ring Kit — موجودی ۱ کیت"}
 ]},
{id:"inv2",title:"کدهای Part Number قطعات",cat:"inventory",machines:["همه"],code:"INV-002",duration:"مرجع",level:"پایه",
 summary:"جدول Part Number قطعات برای سفارش از Elekta Service.",
 warn:"شماره‌کدها نمونه‌اند — برای سفارش حتماً استعلام کنید.",
 tools:["جدول مرجع"],
 steps:[
   {t:"Magnetron MG6026 → ۱۰۱۲۹۹۳۰۰"},
   {t:"Klystron 5MW → ۱۰۱۲۹۹۴۰۰"},
   {t:"MLCi2 Motor Leaf → ۱۵۲۰۴۵۰۰"},
   {t:"MLCi2 Encoder → ۱۵۲۰۴۶۰۰"},
   {t:"Agility Motor → ۱۵۳۰۵۰۰۰"},
   {t:"Agility Leaf → ۱۵۳۰۶۰۰۰"},
   {t:"Ion Chamber → ۱۰۴۵۰۰۱۰"},
   {t:"Target Tungsten → ۱۰۲۳۰۰۲۰"},
   {t:"SF6 Gas بسته → ۸۰۴۵۰۱۰۰"},
   {t:"Coolant → ۹۰۱۲۰۰۱۰"}
 ]},
{id:"inv3",title:"شرایط نگهداری قطعات حساس",cat:"inventory",machines:["همه"],code:"INV-003",duration:"مرجع",level:"پایه",
 summary:"شرایط مناسب برای نگهداری قطعات الکترونیکی و حساس.",
 tools:["کابینت ESD","رطوبت‌سنج"],
 steps:[
   {t:"دمای اتاق انبار: ۱۸–۲۵°C"},
   {t:"رطوبت نسبی: ۴۰–۶۰٪"},
   {t:"بسته‌بندی ضد ESD برای بردها"},
   {t:"کابینت خشک برای Encoder"},
   {t:"دور از تابش مستقیم خورشید"},
   {t:"بازه انقضا برای گریس و چسب"},
   {t:"ثبت ورود و خروج در فرم"}
 ]},
{id:"inv4",title:"سفارش و پیگیری قطعات",cat:"inventory",machines:["همه"],code:"INV-004",duration:"رویه",level:"پایه",
 summary:"فرآیند سفارش قطعه از Elekta Service.",
 tools:["دسترسی Elekta Service Portal"],
 steps:[
   {t:"ورود به service.elekta.com"},
   {t:"جستجوی قطعه با Part Number"},
   {t:"بررسی موجودی و قیمت"},
   {t:"ثبت سفارش"},
   {t:"دریافت Tracking"},
   {t:"بررسی قطعه در هنگام تحویل"},
   {t:"ثبت در سیستم انبار"},
   {t:"نگهداری در محل مناسب"}
 ]},

/* ════════ MLC و کولیما ════════ */
{id:"mlc1",title:"تعویض Leaf MLC (MLCi2 یا Agility)",cat:"mlc",machines:["Synergy","Infinity","Versa HD"],code:"MLC-001",duration:"۲ ساعت",level:"پیشرفته",
 summary:"تعویض یک Leaf آسیب‌دیده یا معیوب.",
 warn:"Leaf باید دقیقاً همان مدل باشد.",
 tools:["آچار مخصوص","فیلر","نرم‌افزار Service"],
 steps:[
   {t:"خاموشی سیستم MLC"},
   {t:"باز کردن پنل بالا"},
   {t:"شناسایی Leaf مشکل‌دار"},
   {t:"جدا کردن کابل Motor و Encoder"},
   {t:"خارج کردن Leaf"},
   {t:"نصب Leaf جدید"},
   {t:"اتصال کابل‌ها"},
   {t:"Auto-Home و کالیبراسیون"},
   {t:"Picket Fence برای تأیید"}
 ]},
{id:"mlc2",title:"QA ماهانه MLC — Picket Fence",cat:"mlc",machines:["Synergy","Infinity","Versa HD"],code:"MLC-002",duration:"۹۰ دقیقه",level:"متوسط",
 summary:"تست ماهانه دقت موقعیت Leaf‌ها با Picket Fence.",
 tools:["فانتوم Picket Fence","فیلم EBT3","اسکنر"],
 steps:[
   {t:"قرارگیری فانتوم در Isocenter"},
   {t:"اجرای فایل Picket Fence"},
   {t:"Development و اسکن فیلم"},
   {t:"تحلیل با نرم‌افزار",note:"انحراف مجاز زیر ۱mm",level:"warn"},
   {t:"تست حرکت تکی هر Leaf"},
   {t:"بررسی هم‌ترازی با کولیما"},
   {t:"اجرای IMRT QA"},
   {t:"ثبت گزارش"}
 ]},
{id:"mlc3",title:"کالیبراسیون کولیما (Jaw)",cat:"mlc",machines:["Synergy","Infinity"],code:"MLC-003",duration:"۲ ساعت",level:"پیشرفته",
 summary:"کالیبراسیون دقیق Jawهای X و Y و هم‌ترازی با MLC.",
 tools:["فانتوم هم‌ترازی","فیلم EBT3"],
 steps:[
   {t:"Service → Collimator → Jaw Calibration"},
   {t:"بررسی موقعیت صفر Jaw X"},
   {t:"بررسی موقعیت صفر Jaw Y"},
   {t:"کالیبراسیون Backlash"},
   {t:"تنظیم Gain"},
   {t:"بررسی هم‌ترازی با MLC",level:"warn"},
   {t:"تست در موقعیت‌های مختلف"},
   {t:"Star Shot برای تأیید"}
 ]},

/* ════════ PM و نگهداری ════════ */
{id:"pm1",title:"چک‌لیست QA روزانه صبحگاهی",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-D-100",duration:"۱۵ دقیقه",level:"پایه",
 summary:"بررسی روزانه صبحگاهی قبل از شروع درمان.",
 tools:["دزیمتر یونیزاسیون","فانتوم روزانه"],
 steps:[
   {t:"روشن کردن و Warm-up (۱۰–۱۵ دقیقه)"},
   {t:"بررسی LEDهای پنل (همه سبز)"},
   {t:"تست Emergency Stop",level:"warn"},
   {t:"اندازه‌گیری دز خروجی",note:"۱۰۰ cGy ± ۳٪"},
   {t:"بررسی حرکت Gantry"},
   {t:"تست میز در سه محور"},
   {t:"بررسی kV/MV imaging"},
   {t:"ثبت در دفتر QA"}
 ]},
{id:"pm2",title:"QA هفتگی دزیمتری",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-W-200",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"اندازه‌گیری خروجی مطلق و پروفایل با فانتوم آب.",
 warn:"انحراف بیش از ۲٪ نیازمند کالیبراسیون فوری است.",
 tools:["فانتوم آب","اتاقک Farmer","الکترومتر"],
 steps:[
   {t:"تنظیم فانتوم روی ۲۰°C"},
   {t:"قرارگیری اتاقک در عمق ۱۰cm"},
   {t:"تابش ۱۰۰ MU",note:"مرجع ۱۰۰ cGy ± ۲٪",level:"warn"},
   {t:"تکرار برای همه انرژی‌ها"},
   {t:"Profile عرضی"},
   {t:"بررسی Flatness و Symmetry"},
   {t:"PDD"},
   {t:"ثبت در فرم QA"}
 ]},
{id:"pm3",title:"کالیبراسیون دز خروجی (Output)",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-CAL-400",duration:"۱۲۰ دقیقه",level:"پیشرفته",
 summary:"کالیبراسیون دز مطلق با پروتکل TRS-398.",
 warn:"فقط توسط فیزیک‌دان پزشکی یا مهندس مجاز.",
 tools:["اتاقک Farmer","الکترومتر","فانتوم آب"],
 steps:[
   {t:"شرایط مرجع (SAD=100، عمق=10cm، میدان ۱۰×۱۰)"},
   {t:"ثبت دما و فشار و محاسبه kTP"},
   {t:"تابش ۱۰۰ MU × ۳ بار"},
   {t:"محاسبه دز جذبی"},
   {t:"مقایسه با مرجع",note:"زیر ۱٪"},
   {t:"اعمال ضریب در Monaco/RayStation"},
   {t:"تکرار برای همه انرژی‌ها"},
   {t:"تست صحت پس از کالیبراسیون"}
 ]},
{id:"pm4",title:"QA سالانه جامع (TG-142)",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-A-500",duration:"۲ روز",level:"پیشرفته",
 summary:"QA سالانه جامع طبق پروتکل AAPM TG-142.",
 warn:"نیازمند تعطیلی موقت دستگاه.",
 tools:["کل ابزارهای QA","چک‌لیست TG-142","تیم کامل"],
 steps:[
   {t:"روز ۱: مکانیک کامل (Isocenter, Gantry, Collimator, Couch)"},
   {t:"روز ۱: Imaging (kV, CBCT, EPID)"},
   {t:"روز ۱: ایمنی کامل"},
   {t:"روز ۲: دزیمتری همه انرژی‌ها"},
   {t:"روز ۲: MLC و IMRT/VMAT"},
   {t:"کالیبراسیون‌های جزئی در صورت نیاز"},
   {t:"گزارش رسمی و ارسال به فیزیک‌دان"}
 ]},
{id:"pm5",title:"Warm-up و Standby روزانه",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-D-110",duration:"۲۰ دقیقه",level:"پایه",
 summary:"رویه استاندارد روشن و خاموش کردن روزانه دستگاه.",
 tools:["دماسنج محیط","چک‌لیست"],
 steps:[
   {t:"بررسی دمای اتاق (۲۰–۲۴°C)"},
   {t:"روشن کردن مانیتورها به ترتیب"},
   {t:"ورود به iGuide/Integrity"},
   {t:"انتظار Warm-up (۱۰ دقیقه)",level:"warn"},
   {t:"بررسی سبز بودن سیستم"},
   {t:"Reset Motors"},
   {t:"Park MLC قبل از خاموشی"},
   {t:"خاموش کردن معکوس"}
 ]},
{id:"pm6",title:"QA هفتگی EPID",cat:"pm",machines:["Synergy","Infinity"],code:"PM-W-210",duration:"۳۰ دقیقه",level:"متوسط",
 summary:"بررسی کیفیت تصویر EPID.",
 tools:["فانتوم EPID","فانتوم Las Vegas"],
 steps:[
   {t:"راه‌اندازی در SID=150cm"},
   {t:"تصویر Dark و Flood"},
   {t:"تصویر فانتوم Las Vegas"},
   {t:"بررسی Uniformity"},
   {t:"تست موقعیت"},
   {t:"مقایسه و ثبت"}
 ]},
{id:"pm7",title:"کالیبراسیون Imaging kV",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-CAL-310",duration:"۶۰ دقیقه",level:"پیشرفته",
 summary:"کالیبراسیون kVp، mA و یکنواختی تصویر.",
 tools:["مولتی‌متر kV","فانتوم"],
 steps:[
   {t:"Service → Imaging → Calibration"},
   {t:"اندازه‌گیری kVp",note:"± ۲٪"},
   {t:"کالیبراسیون Dark و Gain"},
   {t:"بررسی Uniformity"},
   {t:"کالیبراسیون مرکز"},
   {t:"تست Offset"},
   {t:"ذخیره و ری‌استارت"}
 ]},
{id:"pm8",title:"کالیبراسیون CBCT (XVI)",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-CAL-700",duration:"۹۰ دقیقه",level:"پیشرفته",
 summary:"کالیبراسیون هندسی CBCT شامل Isocenter و FlexMap.",
 warn:"توسط تکنسین آموزش‌دیده انجام شود.",
 tools:["فانتوم XVI","ابزار کالیبراسیون"],
 steps:[
   {t:"Service → XVI → Geometry Calibration"},
   {t:"نصب فانتوم در Isocenter"},
   {t:"اسکن ۳۶۰ درجه"},
   {t:"بازبینی — انحراف زیر ۰.۵mm",level:"warn"},
   {t:"اجرای FlexMap"},
   {t:"Reconstruction با CatPhan"},
   {t:"QA XVI"}
 ]},
{id:"pm9",title:"کالیبراسیون لیزرهای اتاق",cat:"pm",machines:["Synergy","Infinity","Versa HD"],code:"PM-CAL-410",duration:"۴۵ دقیقه",level:"متوسط",
 summary:"کالیبراسیون لیزرها با فانتوم Isocenter.",
 tools:["فانتوم هم‌ترازی","فیلر"],
 steps:[
   {t:"قرارگیری فانتوم روی Isocenter"},
   {t:"بررسی سه لیزر (دیواری، سقفی، دوطرفه)",note:"انحراف زیر ۱mm در ۱m"},
   {t:"کالیبراسیون لیزر عرضی"},
   {t:"کالیبراسیون لیزر طولی و عمودی"},
   {t:"بازبینی نهایی"}
 ]}
];

/* ═══════════════════════════════════════
   کدهای خطا — تمرکز سرویسی
   ═══════════════════════════════════════ */
const ERRORS = [
/* ─── RF و Magnetron ─── */
{code:"RF-001",sev:"red",machine:"Synergy / Infinity",title:"Magnetron Overcurrent",act:"بررسی AFC و توان RF"},
{code:"RF-002",sev:"orange",machine:"Synergy / Infinity",title:"Magnetron Frequency Drift",act:"تنظیم AFC در سرویس"},
{code:"RF-003",sev:"red",machine:"Synergy / Infinity",title:"Waveguide Arc Detected",act:"بررسی SF6 و تمیزکاری"},
{code:"RF-004",sev:"orange",machine:"همه Linacها",title:"Klystron Filament Failure",act:"بررسی Filament و تعویض"},
{code:"RF-005",sev:"orange",machine:"Synergy / Infinity",title:"RF Reflected Power High",act:"بررسی Circulator"},
{code:"RF-006",sev:"red",machine:"همه Linacها",title:"Modulator Fault",act:"بررسی PFN و SCR"},
{code:"RF-007",sev:"orange",machine:"Synergy / Infinity",title:"SF6 Pressure Low",act:"شارژ مجدد SF6"},
{code:"RF-008",sev:"red",machine:"Synergy / Infinity",title:"Circulator Failure",act:"تعویض Circulator"},

/* ─── MLC ─── */
{code:"MLC-001",sev:"orange",machine:"Synergy / Infinity",title:"MLC Leaf Position Error",act:"Auto-Home و کالیبراسیون"},
{code:"MLC-002",sev:"red",machine:"همه Linacها",title:"MLC Encoder Mismatch",act:"تعویض Encoder Leaf"},
{code:"MLC-003",sev:"orange",machine:"Synergy / Infinity",title:"MLC Motor Overheat",act:"خنک شدن و بررسی بار"},
{code:"MLC-004",sev:"orange",machine:"Infinity",title:"Agility Backlash Over Limit",act:"تنظیم Backlash"},
{code:"MLC-005",sev:"red",machine:"Infinity",title:"Agility Bank Failure",act:"بررسی Bank — تعویض در صورت نیاز"},

/* ─── مکانیک ─── */
{code:"MEC-001",sev:"red",machine:"همه Linacها",title:"Gantry Interlock (i70)",act:"Reset Motors و بررسی Encoder"},
{code:"MEC-002",sev:"orange",machine:"Synergy / Infinity",title:"Collimator Rotation Error",act:"Reset و کالیبراسیون"},
{code:"MEC-003",sev:"red",machine:"همه Linacها",title:"Couch Position Error",act:"کالیبراسیون Encoder میز"},
{code:"MEC-004",sev:"orange",machine:"همه Linacها",title:"Gantry Angle Misalignment",act:"کالیبراسیون Gantry"},
{code:"MEC-005",sev:"red",machine:"Infinity",title:"HexaPOD Communication Lost",act:"بررسی کابل و ری‌استارت"},
{code:"MEC-006",sev:"orange",machine:"Infinity",title:"HexaPOD Out of Range",act:"Reset موقعیت"},

/* ─── الکترونیک ─── */
{code:"ELC-001",sev:"red",machine:"همه Linacها",title:"Control Board Failure",act:"تعویض برد Control"},
{code:"ELC-002",sev:"red",machine:"Synergy / Infinity",title:"Modulator Board Fault",act:"تعویض برد Modulator"},
{code:"ELC-003",sev:"orange",machine:"Synergy / Infinity",title:"Encoder Board Error",act:"تعویض برد Encoder"},
{code:"ELC-004",sev:"red",machine:"همه Linacها",title:"Power Supply Failure",act:"تعویض Power Supply"},
{code:"ELC-005",sev:"orange",machine:"همه Linacها",title:"Voltage Out of Range",act:"بررسی ولتاژهای تغذیه"},

/* ─── نرم‌افزار ─── */
{code:"SW-001",sev:"red",machine:"همه Linacها",title:"System Crash",act:"Recovery و بازیابی Backup"},
{code:"SW-002",sev:"orange",machine:"همه Linacها",title:"Disk Space Low",act:"پاکسازی و بررسی دیسک"},
{code:"SW-003",sev:"orange",machine:"Infinity",title:"Integrity Service Error",act:"ری‌استارت سرویس"},
{code:"SW-004",sev:"red",machine:"همه Linacها",title:"License Expired",act:"تمدید License"},
{code:"SW-005",sev:"orange",machine:"همه Linacها",title:"DICOM Transfer Failed",act:"بررسی شبکه و AE Title"},

/* ─── خنک‌کننده ─── */
{code:"COOL-001",sev:"red",machine:"همه Linacها",title:"Modulator Over Temperature",act:"بررسی فن و Chiller"},
{code:"COOL-002",sev:"orange",machine:"همه Linacها",title:"Coolant Pressure Low",act:"بررسی پمپ و نشتی"},
{code:"COOL-003",sev:"orange",machine:"همه Linacها",title:"Chiller Over Temperature",act:"بررسی رادیاتور"},
{code:"COOL-004",sev:"orange",machine:"همه Linacها",title:"Coolant Flow Low",act:"بررسی جریان و فیلترها"},

/* ─── ایمنی ─── */
{code:"SAFE-001",sev:"red",machine:"همه Linacها",title:"Door Interlock Failure",act:"توقف فوری — بررسی میکروسوئیچ"},
{code:"SAFE-002",sev:"red",machine:"همه Linacها",title:"Emergency Stop Activated",act:"بررسی و ریست"},
{code:"SAFE-003",sev:"red",machine:"همه Linacها",title:"Beam On with Door Open",act:"بررسی فوری اینترلاک"},

/* ─── تصویربرداری ─── */
{code:"IMG-001",sev:"blue",machine:"همه Linacها",title:"XVI Projection Low",act:"افزایش Acquisition"},
{code:"IMG-002",sev:"orange",machine:"همه Linacها",title:"FlexMap Expired",act:"کالیبراسیون مجدد"},
{code:"IMG-003",sev:"orange",machine:"همه Linacها",title:"Detector Error",act:"بررسی اتصالات Flat Panel"},

/* ─── Brachytherapy ─── */
{code:"BRA-001",sev:"red",machine:"Flexitron",title:"Source Stuck",act:"Manual Retract — Emergency"},
{code:"BRA-002",sev:"orange",machine:"Flexitron",title:"Indexer Error",act:"بررسی کانال"},
{code:"BRA-003",sev:"red",machine:"Flexitron",title:"Door Interlock Failure",act:"توقف فوری"},
{code:"BRA-004",sev:"orange",machine:"Flexitron",title:"Timer Mismatch",act:"کالیبراسیون Timer"},
{code:"BRA-005",sev:"blue",machine:"Flexitron",title:"Source Decay Warning",act:"برنامه‌ریزی تعویض منبع"},

/* ─── عمومی ─── */
{code:"GEN-001",sev:"red",machine:"همه Linacها",title:"Dose Monitor Mismatch",act:"توقف — بررسی اتاقک‌ها"},
{code:"GEN-002",sev:"orange",machine:"همه Linacها",title:"Beam Output Deviation",act:"کالیبراسیون Output"},
{code:"GEN-003",sev:"orange",machine:"همه Linacها",title:"Console Connection Lost",act:"بررسی شبکه"},
{code:"GEN-004",sev:"red",machine:"همه Linacها",title:"Gantry Collision Risk",act:"توقف فوری — بررسی ایمنی"},
{code:"GEN-005",sev:"orange",machine:"همه Linacها",title:"Water Temperature High",act:"بررسی خنک‌کننده"}
];

const MACHINES = ["Synergy","Infinity","Versa HD","Unity","Axesse","Precise","Compact","Flexitron"];